"use client"
import * as React from "react"
import { Archive, ArrowLeft, Bell, Check, CheckCheck, MoreVertical, Users, ShieldCheck, Receipt, TrendingUp, PieChart } from "lucide-react"
import Link from "@/app/components/context-link"
import { Button } from "@/app/components/ui/button"
import { Card } from "@/app/components/ui/card"
import { Logo } from "@/app/components/logo"
import { cn } from "@/app/lib/utils"

type Notification = { id: string; title: string; body: string; category: string; actionUrl?: string; readAt?: string | null }

export default function NotificationsPage() {
  const [items, setItems] = React.useState<Notification[]>([])
  const [loading, setLoading] = React.useState(true)
  const [error, setError] = React.useState<string | null>(null)
  const load = React.useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch('/api/notifications?limit=50', { cache: 'no-store' }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.message || 'Não foi possível carregar as notificações.'); setItems(data?.items || []) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar as notificações.') } finally { setLoading(false) } }, [])
  React.useEffect(() => { void load() }, [load])
  const markRead = async (id: string) => { await fetch(`/api/notifications/${id}/read`, { method: 'PATCH' }); setItems(v => v.map(i => i.id === id ? { ...i, readAt: new Date().toISOString() } : i)) }
  const markAll = async () => { await fetch('/api/notifications/read-all', { method: 'POST' }); setItems(v => v.map(i => ({ ...i, readAt: new Date().toISOString() }))) }
  const archive = async (id: string) => { await fetch(`/api/notifications/${id}`, { method: 'DELETE' }); setItems(v => v.filter(i => i.id !== id)) }
  const iconFor = (category: string) => category.includes('invite') ? Users : category.includes('security') ? ShieldCheck : category.includes('credit') ? TrendingUp : category.includes('debit') ? Receipt : PieChart
  const renderItem = (item: Notification) => { const Icon = iconFor(item.category); const unread = !item.readAt; return <div key={item.id} className={cn('flex gap-3 rounded-2xl border p-4 md:p-5', unread ? 'border-primary/50 bg-primary/[0.07]' : 'border-border/70 bg-background/40')}><div className={cn('flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl', unread ? 'bg-primary/15 text-primary' : 'bg-muted text-muted-foreground')}><Icon className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold leading-tight">{item.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.body}</p></div><div className="flex shrink-0 items-center gap-3 text-xs text-muted-foreground"><span>{unread ? 'Agora' : 'Anteriormente'}</span><MoreVertical className="h-4 w-4" /></div></div><div className="mt-3 flex flex-wrap items-center gap-2">{item.actionUrl && <Link href={item.actionUrl} onClick={() => unread && markRead(item.id)}><Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90">Ver detalhes</Button></Link>}{unread && <Button variant="ghost" size="sm" onClick={() => markRead(item.id)}><Check className="mr-1 h-4 w-4" />Marcar como lida</Button>}<Button variant="ghost" size="sm" onClick={() => archive(item.id)}><Archive className="mr-1 h-4 w-4" />Arquivar</Button></div></div></div> }
  const unread = items.filter(i => !i.readAt)
  return <main className="min-h-screen bg-background pb-24 md:pb-8"><div className="border-b border-border/60 px-4 py-3"><div className="mx-auto flex max-w-4xl items-center justify-between"><Link href="/dashboard" className="flex items-center gap-2"><Logo className="h-7 w-7 text-primary" /><span className="font-semibold">MeControla<span className="text-primary">.AI</span></span></Link><Link href="#" aria-label="Notificações" className="text-muted-foreground"><Bell className="h-5 w-5" /></Link></div></div><div className="mx-auto max-w-4xl space-y-5 p-4 md:p-8"><div className="flex items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-3xl font-bold tracking-tight"><Bell className="h-6 w-6 text-primary" />Notificações</h1><p className="mt-1 text-sm text-muted-foreground">Acompanhe as novidades e ações<br className="sm:hidden" /> importantes da sua caixinha.</p></div>{unread.length > 0 && <Button variant="outline" size="sm" onClick={markAll} className="shrink-0 rounded-full"><CheckCheck className="mr-2 h-4 w-4" />Marcar todas como lidas</Button>}</div><Card className="rounded-2xl border-border/80 bg-card/70 p-4 md:p-6"><h2 className="mb-5 text-lg font-semibold">Sua central de avisos</h2>{loading ? <p className="py-8 text-center text-sm text-muted-foreground">Carregando notificações...</p> : error ? <p className="py-8 text-center text-destructive">{error}</p> : items.length === 0 ? <p className="py-10 text-center text-muted-foreground">Você não tem novas notificações.</p> : <div className="space-y-3">{items.map(renderItem)}</div>}</Card><Link href="/dashboard" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-2 h-4 w-4" />Voltar ao resumo</Link></div></main>
}
