"use client"
import * as React from "react"
import Link from "@/app/components/context-link"
import { Archive, Bell, Check, CheckCheck, MoreVertical, Receipt, ShieldCheck, TrendingUp, Users, PieChart } from "lucide-react"
import { Button } from "@/app/components/ui/button"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/app/components/ui/dropdown-menu"
import { cn } from "@/app/lib/utils"
type Notification = { id: string; title: string; body: string; category: string; actionUrl?: string; readAt?: string | null }
const iconFor = (category: string) => category.includes("invite") ? Users : category.includes("security") ? ShieldCheck : category.includes("credit") ? TrendingUp : category.includes("debit") ? Receipt : PieChart
export default function NotificationsPage() {
  const [items, setItems] = React.useState<Notification[]>([]); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null)
  const load = React.useCallback(async () => { try { const response = await fetch("/api/notifications?limit=50", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data?.message); setItems(data?.items || []) } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar as notificações.") } finally { setLoading(false) } }, [])
  React.useEffect(() => { void load() }, [load]); const markRead = async (id: string) => { await fetch(`/api/notifications/${id}/read`, { method: "PATCH" }); setItems(v => v.map(i => i.id === id ? { ...i, readAt: new Date().toISOString() } : i)) }; const markAll = async () => { await fetch("/api/notifications/read-all", { method: "POST" }); setItems(v => v.map(i => ({ ...i, readAt: new Date().toISOString() }))) }; const archive = async (id: string) => { await fetch(`/api/notifications/${id}`, { method: "DELETE" }); setItems(v => v.filter(i => i.id !== id)) }
  const unread = items.filter(i => !i.readAt), older = items.filter(i => i.readAt)
  const renderItem = (item: Notification) => { const isUnread = !item.readAt, Icon = iconFor(item.category); return <article key={item.id} className={cn("relative grid grid-cols-[52px_minmax(0,1fr)_32px] gap-3 rounded-2xl border p-4 md:grid-cols-[88px_minmax(0,1fr)_110px_32px] md:items-center md:gap-5 md:px-6 md:py-5", isUnread ? "border-primary/50 bg-primary/[0.06]" : "border-border/70 bg-card/40")}><div className={cn("flex h-12 w-12 items-center justify-center rounded-2xl md:h-20 md:w-20", isUnread ? "bg-primary/15 text-primary" : "bg-muted text-muted-foreground")}><Icon className="h-6 w-6 md:h-9 md:w-9" /></div><div className="min-w-0"><h3 className="text-base font-semibold md:text-xl">{item.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground md:text-base">{item.body}</p></div><span className="col-start-2 text-xs text-muted-foreground md:col-start-auto md:text-right md:text-sm">{isUnread ? "Agora" : "Anteriormente"}</span><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="col-start-3 row-start-1 rounded-full text-muted-foreground hover:bg-muted" aria-label={`Ações para ${item.title}`}><MoreVertical className="h-5 w-5" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48"><DropdownMenuItem disabled={!item.actionUrl} onClick={() => item.actionUrl && (window.location.href = item.actionUrl)}>Ver detalhes</DropdownMenuItem>{isUnread && <DropdownMenuItem onClick={() => markRead(item.id)}><Check className="mr-2 h-4 w-4" />Marcar como lida</DropdownMenuItem>}<DropdownMenuSeparator /><DropdownMenuItem className="text-destructive focus:text-destructive" onClick={() => archive(item.id)}><Archive className="mr-2 h-4 w-4" />Arquivar</DropdownMenuItem></DropdownMenuContent></DropdownMenu>{isUnread && <span className="absolute right-12 top-4 h-2.5 w-2.5 rounded-full bg-primary md:right-16 md:top-6" />}</article> }
  return <main className="min-h-screen bg-background pb-24 md:pb-8"><div className="mx-auto max-w-5xl space-y-7 p-4 md:p-8"><div className="flex flex-col items-start gap-3"><div><h1 className="flex items-center gap-2 text-3xl font-bold tracking-tight md:text-5xl"><Bell className="h-7 w-7 text-primary md:h-9 md:w-9" />Notificações</h1><p className="mt-2 text-base text-muted-foreground">Você tem <span className="font-semibold text-primary">{unread.length}</span> {unread.length === 1 ? "novidade" : "novidades"}</p></div>{unread.length > 0 && <Button variant="outline" size="sm" onClick={markAll} className="rounded-full md:px-5 md:py-5 md:text-base"><CheckCheck className="mr-2 h-4 w-4" />Marcar todas como lidas</Button>}</div>{loading ? <p className="py-12 text-center text-muted-foreground">Carregando notificações...</p> : error ? <p className="py-12 text-center text-destructive">{error}</p> : <div className="space-y-7"><section><h2 className="mb-4 text-2xl font-semibold">Hoje</h2><div className="space-y-4">{unread.length ? unread.map(renderItem) : <p className="rounded-2xl border border-dashed border-border p-8 text-center text-muted-foreground">Nenhuma novidade por aqui.</p>}</div></section>{older.length > 0 && <section><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-semibold">Anteriormente</h2><Button variant="link" className="text-primary">Ver todas</Button></div><div className="space-y-4">{older.map(renderItem)}</div></section>}</div>}<Link href="/dashboard" className="inline-flex items-center text-sm text-muted-foreground"><span className="mr-2">←</span>Voltar ao resumo</Link></div></main>
}
