"use client"
import { useEffect, useState } from "react"
import { Bell, Mail, Smartphone, Trash2 } from "lucide-react"
import { PushNotificationRegistration } from "@/app/components/push-notification-registration"

export function NotificationPreferences() {
  const [preferences, setPreferences] = useState({ pushEnabled: true, emailEnabled: true })
  const [saving, setSaving] = useState(false)
  const [devices, setDevices] = useState<{ id: string; endpoint: string; userAgent?: string | null; updatedAt?: string | null }[]>([])
  useEffect(() => { fetch('/api/notification-preferences').then(r => r.ok ? r.json() : null).then(data => data && setPreferences(data)).catch(() => undefined); fetch('/api/push/subscribe').then(r => r.ok ? r.json() : null).then(data => data && setDevices(data.devices || [])).catch(() => undefined) }, [])
  async function update(key: 'pushEnabled' | 'emailEnabled', value: boolean) { setSaving(true); setPreferences(current => ({ ...current, [key]: value })); const response = await fetch('/api/notification-preferences', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [key]: value }) }); if (!response.ok) setPreferences(current => ({ ...current, [key]: !value })); setSaving(false) }
  async function removeDevice(device: { endpoint: string }) { await fetch('/api/push/subscribe', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ endpoint: device.endpoint }) }); setDevices(current => current.filter(item => item.endpoint !== device.endpoint)) }
  function deviceName(userAgent?: string | null) { if (!userAgent) return 'Navegador desconhecido'; if (/Android/i.test(userAgent)) return 'Celular Android'; if (/iPhone|iPad/i.test(userAgent)) return 'iPhone ou iPad'; if (/Windows/i.test(userAgent)) return 'Windows'; if (/Macintosh/i.test(userAgent)) return 'Mac'; return 'Navegador' }
  return <div className="space-y-4"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><Bell className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-semibold">Notificações push</p><p className="text-xs text-muted-foreground">Avisos no navegador e no celular.</p></div></div><input aria-label="Notificações push" type="checkbox" checked={preferences.pushEnabled} onChange={event => update('pushEnabled', event.target.checked)} disabled={saving} className="mt-1 h-4 w-4 accent-primary" /></div><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><Mail className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-semibold">Notificações por e-mail</p><p className="text-xs text-muted-foreground">Receba comunicações importantes por e-mail.</p></div></div><input aria-label="Notificações por e-mail" type="checkbox" checked={preferences.emailEnabled} onChange={event => update('emailEnabled', event.target.checked)} disabled={saving} className="mt-1 h-4 w-4 accent-primary" /></div><div className="border-t pt-4"><PushNotificationRegistration /></div>{devices.length > 0 && <div className="border-t pt-4"><p className="mb-2 text-sm font-semibold">Dispositivos registrados</p><div className="space-y-2">{devices.map(device => <div key={device.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="flex min-w-0 items-center gap-2"><Smartphone className="h-4 w-4 shrink-0 text-muted-foreground" /><div className="min-w-0"><p className="truncate text-sm font-medium">{deviceName(device.userAgent)}</p><p className="text-xs text-muted-foreground">Atualizado em {device.updatedAt ? new Date(device.updatedAt).toLocaleDateString('pt-BR') : 'data desconhecida'}</p></div></div><button type="button" aria-label={`Remover ${deviceName(device.userAgent)}`} onClick={() => removeDevice(device)} className="rounded-md p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-4 w-4" /></button></div>)}</div></div>}</div>
}
